image: docker
services:
  - docker:dind

stages:
  - test
  - deploy

test:
  tags:
    - cognate
  stage: test
  script:
    - echo "no tests written yet :("

deploy:
  tags:
    - cognate
  stage: deploy
  only:
    refs:
      - main
  before_script:
    - docker-compose version
  script:
    - echo "Building Docker and Postgre"
    - docker-compose down
    - docker-compose up -d --build
  environment: main

