image: docker
services:
  - docker:dind

variables:
  GITLAB_TOKEN: $GITLAB_TOKEN

stages:
  - deploy
  - deploy-dev

deploy:
  tags:
    - cognate
  stage: deploy
  only:
    refs:
      - main
  before_script:
    - docker-compose version
    - echo GITLAB_TOKEN=$GITLAB_TOKEN >> .env
  script:
    - echo "Building Docker and Postgre"
    - docker-compose stop
    - docker-compose up -d --build
    - docker exec django sh -c "service cron start"
  environment: main

deploy-dev:
  tags:
    - cognate-dev
  stage: deploy
  only:
    refs:
      - develop
  before_script:
    - docker-compose version
    - echo GITLAB_TOKEN=$GITLAB_TOKEN >> .env
  script:
    - echo "Building Docker and Postgre"
    - docker-compose stop
    - docker-compose up -d --build
    - docker exec django sh -c "service cron start"