services:
  django:
    build: .
    container_name: django
    image: cognate/back
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runsslserver 0.0.0.0:8081"
    volumes:
      - .:/usr/src/app
    ports:
      - "8081:8081"
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - cognate-db-data:/var/lib/postgresql/data

volumes:
  cognate-db-data: