# Generated by Django 4.0 on 2022-01-21 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0003_rename_project_group_projectgroup_parent_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergrade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprojectgroup',
            name='user',
        ),
        migrations.AddField(
            model_name='usergrade',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproject',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprojectgroup',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Committer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.committer'),
        ),
        migrations.AlterField(
            model_name='timespent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.committer'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
