# Generated by Django 4.0 on 2022-01-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0004_remove_usergrade_user_remove_userproject_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committer',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='gradecalculation',
            name='grade_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.gradecategory'),
        ),
        migrations.AlterField(
            model_name='gradecategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.gradecategory'),
        ),
        migrations.AlterField(
            model_name='gradecomponent',
            name='grade_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.gradecategory'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='grade_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.grademilestone'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.projectgroup'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.projectgroup'),
        ),
    ]
