# Generated by Django 4.0 on 2022-01-22 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_committer_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprojectgroup',
            name='project_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project_groups', to='app.projectgroup'),
        ),
    ]
