# Generated by Django 4.0 on 2022-02-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_project_name_repository_gitlab_id_repository_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecategory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
