# Generated by Django 4.0 on 2022-02-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_gradecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecalculation',
            name='grade_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.gradecategory'),
        ),
        migrations.AlterField(
            model_name='gradecalculation',
            name='project_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.projectgroup'),
        ),
    ]
