# Generated by Django 4.0 on 2022-02-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_gradecalculation_grade_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecalculation',
            name='grade_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_calculation', to='app.gradecategory'),
        ),
    ]
