# Generated by Django 4.0 on 2022-02-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_gradecalculation_grade_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecalculation',
            name='project_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_calculation', to='app.projectgroup'),
        ),
    ]
