# Generated by Django 4.0 on 2022-02-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_gradecalculation_project_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecomponent',
            name='grade_type',
            field=models.CharField(choices=[('C', 'Custom')], default='C', max_length=1),
        ),
    ]
