# Generated by Django 4.0 on 2022-02-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_gradecomponent_grade_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grademilestone',
            name='grade_component',
        ),
        migrations.AddField(
            model_name='grademilestone',
            name='grade_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gradecategory'),
        ),
    ]
