# Generated by Django 4.0 on 2022-02-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_grademilestone_grade_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grademilestone',
            name='grade_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gradecategory'),
        ),
    ]
