# Generated by Django 4.0 on 2022-02-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_grademilestone_grade_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='actual_account',
            field=models.BooleanField(default=True),
        ),
    ]
