# Generated by Django 4.0 on 2022-02-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profile_actual_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradecategory',
            name='grade_type',
            field=models.CharField(choices=[('C', 'Custom'), ('S', 'Sum'), ('M', 'Max')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='gradecategory',
            name='total',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usergrade',
            name='grade_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gradecategory'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='rights',
            field=models.CharField(choices=[('A', 'Admin'), ('O', 'Owner'), ('V', 'Viewer'), ('M', 'Member')], default='V', max_length=1),
        ),
        migrations.DeleteModel(
            name='GradeComponent',
        ),
    ]
