# Generated by Django 4.0 on 2022-02-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_gradecategory_description_gradecategory_grade_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.gradecategory'),
        ),
    ]
