# Generated by Django 4.0 on 2022-02-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_gradecategory_total_alter_usergrade_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecategory',
            name='grade_type',
            field=models.CharField(choices=[('C', 'Custom'), ('S', 'Sum'), ('M', 'Max'), ('I', 'Min')], default='C', max_length=1),
        ),
    ]
