# Generated by Django 4.0 on 2022-02-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_usergrade_account_usergrade_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='gitlab_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestone',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='app.repository'),
        ),
    ]
