# Generated by Django 4.0 on 2022-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_milestone_gitlab_id_milestone_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuemilestone',
            name='end',
        ),
        migrations.RemoveField(
            model_name='issuemilestone',
            name='start',
        ),
        migrations.AddField(
            model_name='issue',
            name='gitlab_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
