# Generated by Django 4.0 on 2022-02-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_issuemilestone_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='gitlab_iid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
