# Generated by Django 4.0 on 2022-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_timespent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timespent',
            name='gitlab_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
