# Generated by Django 4.0 on 2022-02-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_project_gitlab_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrade',
            name='grade_type',
            field=models.CharField(choices=[('P', 'Placeholder'), ('A', 'Automatic'), ('M', 'Manual')], default='P', max_length=1),
        ),
    ]
