# Generated by Django 4.0 on 2022-02-16 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_project_gitlab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecategory',
            name='grade_type',
            field=models.CharField(choices=[('C', 'Custom'), ('S', 'Sum'), ('M', 'Max'), ('I', 'Min'), ('A', 'Automatic')], default='C', max_length=1),
        ),
        migrations.CreateModel(
            name='AutomateGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_type', models.CharField(choices=[('R', 'Random'), ('T', 'Time spent'), ('L', 'Lines added')], default='R', max_length=1)),
                ('amount_needed', models.IntegerField()),
                ('grade_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gradecategory')),
            ],
        ),
    ]
