# Generated by Django 4.0 on 2022-02-17 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_gradecategory_grade_type_automategrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergrade',
            old_name='grade_component',
            new_name='grade_category',
        ),
    ]
