# Generated by Django 4.0 on 2022-02-17 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_grade_component_usergrade_grade_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='app.milestone'),
        ),
        migrations.DeleteModel(
            name='IssueMilestone',
        ),
    ]
