# Generated by Django 4.0 on 2022-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='grademilestone',
            name='milestone_order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
