# Generated by Django 4.0 on 2022-03-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_grademilestone_milestone_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='has_been_moved',
            field=models.BooleanField(default=False),
        ),
    ]
