# Generated by Django 4.0 on 2022-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
