# Generated by Django 4.0 on 2022-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_process_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='id_hash',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
