# Generated by Django 4.0 on 2022-03-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_process_id_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='grade_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.grademilestone'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('AP', 'Application'), ('PA', 'Project'), ('PM', 'Project milestone'), ('UA', 'User'), ('UM', 'User milestone')], default='AP', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.userproject'),
        ),
    ]
