# Generated by Django 4.0 on 2022-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_feedback_commenter_feedback_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
