# Generated by Django 4.0 on 2022-03-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_userproject_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='gitlab_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
