# Generated by Django 4.0 on 2022-03-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_milestone_gitlab_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='rights',
            field=models.CharField(choices=[('A', 'Admin'), ('O', 'Owner'), ('V', 'Viewer'), ('M', 'Member'), ('E', 'Mentor'), ('T', 'Teacher')], default='V', max_length=1),
        ),
    ]
