# Generated by Django 4.0 on 2022-04-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_userproject_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='gitlab_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='rights',
            field=models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('T', 'Teacher'), ('E', 'Mentor'), ('M', 'Member'), ('V', 'Viewer')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprojectgroup',
            name='rights',
            field=models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('V', 'Viewer')], default='V', max_length=1),
        ),
    ]
