# Generated by Django 4.0 on 2022-04-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_issue_gitlab_link_alter_userproject_rights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committer',
            name='uni_id',
        ),
        migrations.AddField(
            model_name='committer',
            name='name',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committer',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
