# Generated by Django 4.0 on 2022-04-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_committer_uni_id_committer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='colour',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
