# Generated by Kristjan on 2022-04-11 07:09

import random

from django.db import migrations, models
from app.models import UserProject

def generate_random_colour(apps, schema_editor):
    for user_project in UserProject.objects.all():
        if user_project.colour is not None:
            continue
        user_project.colour = "".join([random.choice("0123456789abcdef") for _ in range(6)])
        user_project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_userproject_colour'),
    ]

    operations = [
        migrations.RunPython(generate_random_colour),
    ]
