# Generated by Kristjan on 2022-04-14 11:34

import random
import colorsys

from django.db import migrations, models
from app.models import UserProject


def rgb_to_hex(rgb):
    return '%02x%02x%02x' % rgb


def generate_random_colour(apps, schema_editor):
    for user_project in UserProject.objects.all():
        # Generate random HSV colour, ranges given by Mary
        h = random.random()
        s = 0.6 + random.random() * 0.15
        v = 0.7 + random.random() * 0.1
        rgb = colorsys.hsv_to_rgb(h, s, v)
        user_project.colour = rgb_to_hex((int(rgb[0] * 255), int(rgb[1] * 255), int(rgb[2] * 255)))
        user_project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_random_colour_field'),
    ]

    operations = [
        migrations.RunPython(generate_random_colour),
    ]
