# Generated by Django 4.0 on 2022-04-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_random_colour_field_but_better'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('P', 'Placeholder'), ('A', 'Automatic'), ('M', 'Manual')], default='P', max_length=1)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=100)),
                ('grade_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gradecategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
