# Generated by Django 4.0 on 2022-04-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_projectgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecategory',
            name='project_grade',
            field=models.BooleanField(default=False),
        ),
    ]
