# Generated by Django 4.0 on 2022-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_gradecategory_project_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='colour',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
