# Generated by Django 4.0 on 2022-04-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_projectgroup_gitlab_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.CharField(choices=[('SG', 'Sync group'), ('SR', 'Sync repo')], max_length=2),
        ),
    ]
