# Generated by Django 4.0 on 2022-04-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_milestone_project_alter_milestone_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='app.repository'),
        ),
    ]
