# Generated by Django 4.0 on 2022-05-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_issue_assignee_issue_author_issue_closed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='counted_in_user_project_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproject',
            name='total_lines_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userproject',
            name='total_lines_removed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grademilestone',
            name='grade_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_milestone', to='app.gradecategory'),
        ),
    ]
