# Generated by Django 4.0 on 2022-05-01 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_commit_counted_in_user_project_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_issue_sync',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
