# Generated by Django 4.0 on 2022-05-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_rename_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentcategory',
            old_name='grade_type',
            new_name='assessment_type',
        ),
        migrations.RenameField(
            model_name='assessmentcategory',
            old_name='project_grade',
            new_name='project_assessment',
        ),
        migrations.RenameField(
            model_name='automateassessment',
            old_name='grade_category',
            new_name='assessment_category',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='grade_milestone',
            new_name='assessment_milestone',
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='grade_milestone',
            new_name='assessment_milestone',
        ),
        migrations.RenameField(
            model_name='projectassessment',
            old_name='grade_category',
            new_name='assessment_category',
        ),
        migrations.RenameField(
            model_name='projectassessment',
            old_name='grade_type',
            new_name='assessment_type',
        ),
        migrations.RenameField(
            model_name='userassessment',
            old_name='grade_category',
            new_name='assessment_category',
        ),
        migrations.RenameField(
            model_name='userassessment',
            old_name='grade_type',
            new_name='assessment_type',
        ),
        migrations.RenameField(
            model_name='assessmentcalculation',
            old_name='grade_category',
            new_name='assessment_category',
        ),
        migrations.RenameField(
            model_name='assessmentmilestone',
            old_name='grade_category',
            new_name='assessment_category',
        ),
        migrations.AlterField(
            model_name='assessmentcalculation',
            name='project_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_calculation', to='app.projectgroup'),
        ),
    ]
