# Generated by Django 4.0 on 2022-05-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_rename_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcalculation',
            name='assessment_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_calculation', to='app.assessmentcategory'),
        ),
        migrations.AlterField(
            model_name='assessmentmilestone',
            name='assessment_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_milestone', to='app.assessmentcategory'),
        ),
    ]
