# Generated by Django 4.0 on 2022-05-26 12:37

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_assessmentcalculation_assessment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identifier',
            field=models.CharField(default=app.models.identifier_generator, max_length=32),
        ),
        migrations.CreateModel(
            name='ProjectGroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app.projectgroup')),
            ],
        ),
    ]
