# Generated by Kristjan on 2022-05-26 16:18

import random

from django.db import migrations


def random_hex():
    return ''.join([random.choice("0123456789abcdef") for _ in range(32)])


def generate_new_random_identifiers(apps, schema_editor):
    Profile = apps.get_model('app', 'Profile')
    for profile in Profile.objects.all():
        profile.identifier = random_hex()
        profile.save()


def unset_random_identifiers(apps, schema_editor):
    pass  # Don't need special logic for reversing this


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_profile_identifier_projectgroupinvitation'),
    ]

    operations = [
        migrations.RunPython(generate_new_random_identifiers, unset_random_identifiers),
    ]
