# Generated by Django 4.0 on 2022-05-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_randomize_identifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='rights',
            field=models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('T', 'Teacher'), ('E', 'Mentor'), ('M', 'Member'), ('V', 'Viewer'), ('B', 'Blank')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprojectgroup',
            name='rights',
            field=models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('V', 'Viewer'), ('B', 'Blank')], default='V', max_length=1),
        ),
    ]
