# Generated by Django 4.0 on 2022-05-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_userproject_rights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroupinvitation',
            name='has_been_declined',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
