# Generated by Django 4.0 on 2022-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_projectgroupinvitation_has_been_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroupinvitation',
            name='has_been_declined',
            field=models.BooleanField(default=False),
        ),
    ]
