# Generated by Django 4.0 on 2022-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_projectgroupinvitation_has_been_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gitlab_token_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
