# Generated by Kristjan on 2022-05-30 07:40

from django.db import migrations
from app.models import UserProject, UserProjectGroup


def give_blank_role_to_everyone(apps, schema_editor):
    for user_project in UserProject.objects.all():
        project = user_project.project
        project_group = project.project_group
        if UserProjectGroup.objects.filter(account=user_project.account).filter(project_group=project_group).count() == 0:
            UserProjectGroup.objects.create(rights="B", account=user_project.account, project_group=project_group)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_profile_gitlab_token_salt'),
    ]

    operations = [
        migrations.RunPython(give_blank_role_to_everyone),
    ]
