# Generated by Kristjan on 2022-05-30 07:40

from django.db import migrations


def give_blank_role_to_everyone(apps, schema_editor):
    UserProject = apps.get_model('app', 'UserProject')
    UserProjectGroup = apps.get_model('app', 'UserProjectGroup')
    for user_project in UserProject.objects.all():
        project = user_project.project
        project_group = project.project_group
        if UserProjectGroup.objects.filter(account=user_project.account).filter(project_group=project_group).count() == 0:
            UserProjectGroup.objects.create(rights="B", account=user_project.account, project_group=project_group)


def ungive_roles(apps, schema_editor):
    pass  # Don't need special logic for reversing


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_profile_gitlab_token_salt'),
    ]

    operations = [
        migrations.RunPython(give_blank_role_to_everyone, ungive_roles),
    ]
