# Generated by Django 4.0 on 2022-05-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_blank_role_for_everyone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='store_passwords_in_local_storage',
            field=models.BooleanField(default=False),
        ),
    ]
