# Generated by Django 4.0 on 2022-06-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_issue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automateassessment',
            name='automation_type',
            field=models.CharField(choices=[('R', 'Random'), ('T', 'Time spent'), ('L', 'Lines added'), ('CM', 'Unique commit messages'), ('CW', 'Average word count in commit messages'), ('IW', 'Average word count in issue descriptions'), ('IA', 'Issue amount'), ('CA', 'Commit amount')], default='R', max_length=2),
        ),
    ]
